### PR TITLE
pub sub retry when service instance is not initialized

### PR DESCRIPTION
**Pull request by andrii33**

### CODE REVIEW

**Comment by ankurjain86** [comment]
@andrii33  can you please update the quadro version and changelog as well

**Comment by igorshapiro** [comment]
It looks like a hack to me. No message should be acknowledged/rejected until the processor is initialized.
Or I didn't understand the intent of it?

**Comment by andrii33** [comment]
@igorshapiro All the dead messages from m2adapter being without retries and without last error. The only one place where we do not add the error is one that I changed in the quadro 1.0.8 version.

From the dead messages graph, I see that we removing messages with some period.
Do we reinitialize services with some period in quadro?

**Comment by andrii33** [comment]
@ankurjain86 Updated

**Comment by tomeresk** [comment]
@igorshapiro For some reason right now messages are starting to be processed before the handler is initialized, and current code just sends those message straight to dead queue.

This fix won't solve the messages being processed too early, but it will make sure that they are retried later instead of going to dead queue

**Pull request closed without merging**
