### PR TITLE
Pub sub init order

### PR DESCRIPTION
**Pull request by igorshapiro**

### CODE REVIEW

**Comment by igorshapiro** [comment]
@andrii33 Seems like this is the correct approach. Did you test it?

**Comment by andrii33** [comment]
@igorshapiro  Yes. It was tested and we do not remove messages. 
@ankurjain86  Can we remove pubsub:hubMessageConsumer? With the current code, we do not need it.

**Comment by ankurjain86** [comment]
@andrii33 yes we can remove pubsub:hubMessageConsumer. 
Also we need to update the version and change log before we can merge this.

**Comment by igorshapiro** [comment]
@andrii33 Can you please also fix the codeclimate (remove the redundant files) and I'll merge and publish it

**Comment by andrii33** [comment]
@ankurjain86 Can you review the changes and prepare the new version, please?

**Pull request merged**
